### PR TITLE
Foundation setup

### PR DESCRIPTION
**Pull request by lsf37**
This PR adds SPDX identifiers, basic required foundation docs, and SPDX license tags.

It also fixes code style, since this is now checked automatically for each PR.

### CODE REVIEW

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by lsf37** [comment]
The license check on bamboo will fail as long as that test is not yet switched to spdx checks instead.

**Review by zaklogician — APPROVED** [review]

**Review by zaklogician — COMMENTED** [review]
Sorry, I did not mean to approve all changes just yet, only ones in a specific commit. There seems to be no way to undo it, though :/

**Comment by lsf37** [comment]
> Sorry, I did not mean to approve all changes just yet, only ones in a specific commit. There seems to be no way to undo it, though :/

No worries, you can un-approve I think, but I'll wait for @oliver-wm to have a look through it as well. For that many files two sets of eyes are better. Mostly to look out for: things that I might have accidentally screwed around the headers when I was converting them.

It might be easier to review by commit, because the style commit at the end will have lots of whitespace changes that might distract from the rest.

**Review by oliver-wm — APPROVED** [review]
LGTM :+1:

**Pull request merged**
